### ISSUE TITLE
Domain ID doesn't persist when the Docker container is shut down

### ISSUE THREAD

**Issue by rht** [inblockio/DataAccounting#56]
We need to put the Domain ID metadata file in a directory that persists across shutdowns.

**Comment by FantasticoFox** [comment]
Did we solve this? I still think we should store the Domain ID in the backup folder or in somewhere else to have it persistent. Can't remember if we fixed this already?

**Comment by rht** [comment]
Still not yet. domain_id.txt is located at /var/www/html, which doesn't persist after a `docker-compose down`. It needs to be relocated to be within the DataAccounting extension dir.

**Comment by FantasticoFox** [comment]
Fixed in the micro-pkc by making the domain-id persistent in the config.

**Comment by FantasticoFox** [comment]
Issue is not resolved. We need to rework the way how we backup and restore the Localsettings.php as currently this creates also issues with 'Locked Database' after Backup procedure.

**Comment by rht** [comment]
That's a backup-restore problem and should be solved there. If not nuked, the domain ID persists as long as LocalSettings.php is preserved.

**Comment by FantasticoFox** [comment]
Solved by creating backup of Localsettings.php in the mount point
